print("\'Hi! I'm Eli.\'")
print("The title of the book was \'Good Omens\'.")
print("Hi! I\'m Sebastien.")
print("a\tb\tc")
name = "John Smythe"
print(name.lower())
print(name)
print(float(8.8))
print(int(8.8))
print(str(8.8))
print(str(8))
print(float(8))
print(bool(8))
name1 = input("First name?")
print("Your first name is:" +name1)
name2 = input("Last name?")
print("Your last name is:" +name2)
print(name2+name1)
print("Twinkle, twinkle, little star,\n\tHow I wonder what you are!\n\t\tUp above the world so high,\n\t\tLike a diamond in the sky.\nTwinkle, twinkle, little star, \n\tHow I wonder what you are")
print()
food1=input("Your favorite food?")
food2=input("Your second favorite food?")
print(food1+food2)
print()
