print("Hello, World!")
print("Hello, World again!")
print('Game Over')
print("Game" "over")
print("Game", "Over")
print("Game"," Over")
print('Game Over')
print("Here", end= " ")
print("it is...")
print("a")
print()
print("b")
print("Here")
print("it is ...")
print("Here", end=" ")
print("it is...")
print("A message",
      "a bit",
      "longer")
print()
print("a\nb")
print("c\td")
print("e\\f")
print("g\"h")
print("i\'j")
print("\a")
print("\a\a\a\a")
print("\'")
print("\"hi\"")
print("snow"+"ball")
print("Pie" *30,"STAR","Pie"*10)
print(2+3)
print(1726868%14)

name = "Gaon"
name = input("Hi! What's your name?")
print("Your name is:" +name)
